String VARENYA_POSTS_BOX = "VARENYA_POSTS_BOX";
String VARENYA_DOCTORS_BOX = "VARENYA_DOCTORS_BOX";
String VARENYA_APPOINTMENT_BOX = "VARENYA_APPOINTMENT_BOX";

String VARENYA_APPOINTMENT_LIST = "VARENYA_APPOINTMENT_LIST";
